/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Description = string;
export type Action = string;
export type Target = string | null;
export type Trigger = string;
export type Effects = EffectConfig[];
export type Equipment = string[];
export type Id = string;
export type Name = string;
export type SkillProficiencies = string[];
export type ToolProficiencies = string[];
export type Backgrounds = BackgroundResponse[];
export type CampaignId = string;
export type ContextVersion = number;
export type EncounterId = string | null;
export type SceneId = string | null;
export type CampaignContext = CampaignContextResponse[];
export type Description1 = string | null;
export type DmId = string | null;
export type Name1 = string;
export type CampaignCreate = CampaignCreate1[];
export type ActiveEncounterId = string | null;
export type AbilityIds = string[];
export type Actions = {
  [k: string]: unknown;
}[];
export type Alignment = string | null;
export type ArmorClass = number;
export type BackgroundId = string | null;
export type CampaignId1 = string | null;
export type Description2 = string;
export type Effects1 = EffectConfig[];
export type HitDie = string;
export type Id1 = string;
export type Name2 = string;
export type Progression = {
  [k: string]: unknown;
}[];
export type SavingThrows = string[];
export type Charisma = number;
export type ClassId = string;
export type Constitution = number;
export type CurrentHp = number;
export type Dexterity = number;
export type Description3 = string | null;
export type Name3 = string;
export type Source = string | null;
export type Target1 = string;
export type Type = "BONUS" | "SET";
export type Value1 = number;
export type Effects2 = Effect[];
export type HitDice = string;
export type Id2 = string;
export type Initiative = number;
export type Intelligence = number;
export type Attuned = boolean;
export type CurrentCharges = number | null;
export type CustomName = string | null;
export type Equipped = boolean;
export type Id3 = string;
export type ItemId = string;
export type Quantity = number;
export type Description4 = string | null;
export type Effects3 = Effect[];
export type Id4 = string;
export type Name4 = string;
export type Price = number;
export type Rarity = string;
export type Type1 = string;
export type Weight = number;
export type Inventory = ItemInstance[];
export type Level = number;
export type MaxHp = number;
export type Name5 = string;
export type PlayerId = string | null;
export type PlayerName = string | null;
export type Description5 = string;
export type Effects4 = EffectConfig[];
export type Id5 = string;
export type Languages = string[];
export type Name6 = string;
export type Size = string;
export type Speed = number;
export type Traits = {
  [k: string]: unknown;
}[];
export type SpeciesId = string;
export type Speed1 = number;
export type Spells = {
  [k: string]: unknown;
}[];
export type Status = string;
export type Strength = number;
export type TempHp = number;
export type Wisdom = number;
export type Xp = number;
export type Characters = CharacterResponse[];
export type ContextVersion1 = number;
export type CurrentScene = string | null;
export type Description6 = string | null;
export type DmId1 = string | null;
export type Id6 = string;
export type Name7 = string;
export type Role = string | null;
export type Campaigns = CampaignResponse[];
export type AbilityIds1 = string[];
export type Actions1 = {
  [k: string]: unknown;
}[];
export type Alignment1 = string | null;
export type ArmorClass1 = number;
export type BackgroundId1 = string | null;
export type CampaignId2 = string | null;
export type Charisma1 = number;
export type ClassId1 = string;
export type Constitution1 = number;
export type CurrentHp1 = number;
export type Dexterity1 = number;
export type Effects5 = Effect[];
export type HitDice1 = string;
export type Initiative1 = number;
export type Intelligence1 = number;
export type Inventory1 = ItemInstance[];
export type Level1 = number;
export type MaxHp1 = number;
export type Name8 = string;
export type PlayerId1 = string | null;
export type PlayerName1 = string | null;
export type SpeciesId1 = string;
export type Speed2 = number;
export type Spells1 = {
  [k: string]: unknown;
}[];
export type Status1 = string;
export type Strength1 = number;
export type TempHp1 = number;
export type Wisdom1 = number;
export type Xp1 = number;
export type CharacterCreate = CharacterCreate1[];
export type Characters1 = CharacterResponse[];
export type Classes = ClassResponse[];
export type EncounterId1 = string;
export type Name9 = string;
export type SceneId1 = string;
export type EncounterOptions = EncounterOptionResponse[];
export type Description7 = string | null;
export type Effects6 = Effect[];
export type Name10 = string;
export type Price1 = number;
export type Rarity1 = string;
export type Type2 = string;
export type Weight1 = number;
export type ItemCreate = ItemCreate1[];
export type Items = ItemResponse[];
export type ActionId = string;
export type DisplayName = string | null;
export type Actions2 = MonsterActionRef[];
export type Alignment2 = string;
export type ArmorClass2 = number;
export type ChallengeRating = number;
export type Charisma2 = number;
export type Constitution2 = number;
export type Description8 = string | null;
export type Dexterity2 = number;
export type Effects7 = Effect[];
export type HitDice2 = string;
export type HitPoints = number;
export type Intelligence2 = number;
export type Inventory2 = {
  [k: string]: unknown;
}[];
export type Languages1 = string;
export type LegendaryActions = {
  [k: string]: unknown;
}[];
export type Name11 = string;
export type Proficiencies1 = {
  [k: string]: unknown;
}[];
export type Size1 = string;
export type SpecialAbilities = {
  [k: string]: unknown;
}[];
export type Strength2 = number;
export type Type3 = string;
export type Wisdom2 = number;
export type Xp2 = number;
export type MonsterCreate = MonsterCreate1[];
export type Actions3 = MonsterActionRef[];
export type Alignment3 = string;
export type ArmorClass3 = number;
export type ChallengeRating1 = number;
export type Charisma3 = number;
export type Constitution3 = number;
export type Description9 = string | null;
export type Dexterity3 = number;
export type Effects8 = Effect[];
export type HitDice3 = string;
export type HitPoints1 = number;
export type Id7 = string;
export type Intelligence3 = number;
export type Inventory3 = {
  [k: string]: unknown;
}[];
export type Languages2 = string;
export type LegendaryActions1 = {
  [k: string]: unknown;
}[];
export type Name12 = string;
export type Proficiencies2 = {
  [k: string]: unknown;
}[];
export type Size2 = string;
export type SpecialAbilities1 = {
  [k: string]: unknown;
}[];
export type Strength3 = number;
export type Type4 = string;
export type Wisdom3 = number;
export type Xp3 = number;
export type Monsters = MonsterResponse[];
export type Name13 = string;
export type SceneId2 = string;
export type SceneOptions = SceneOptionResponse[];
export type EncounterId2 = string;
export type SceneId3 = string;
export type SelectCampaignContextRequest = SelectCampaignContextRequest1[];
export type Species = SpeciesResponse[];
export type CastingTime = string;
export type Description10 = string | null;
export type Duration = string;
export type Effects9 = EffectConfig[];
export type Level2 = number;
export type Name14 = string;
export type Range = string;
export type School = string;
export type SpellCreate = SpellCreate1[];
export type CastingTime1 = string;
export type Description11 = string | null;
export type Duration1 = string;
export type Effects10 = EffectConfig[];
export type Id8 = string;
export type Level3 = number;
export type Name15 = string;
export type Range1 = string;
export type School1 = string;
export type Spells2 = SpellResponse[];
export type AbilityType = "feature" | "feat";
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ActivationCost".
 */
export type ActivationCost = "action" | "bonus_action" | "reaction" | "free";
export type ActivationTrigger = string | null;
export type OperationId = string;
export type Payload = AttackRollPayload | SavePayload | HealPayload | EffectApplicationPayload;
export type AttackType = "melee_weapon" | "ranged_weapon" | "melee_spell" | "ranged_spell";
export type CriticalThreshold = number;
export type AddStatModifier = boolean;
export type DamageType = string;
export type Value2 = string | number | ResultReference;
/**
 * Identifies specific data points output by an operation in the V2 graph.
 * NOTE: This list is an initial draft and will be extended as V2 mechanics evolve.
 *
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ResultAttribute".
 */
export type ResultAttribute = "total_damage" | "actual_heal" | "base_die_roll" | "saving_throw_margin" | "target_count";
export type Bonus = number;
export type Multiplier = number;
export type SourceOperationId = string;
export type DamageInstances = DamageInstance[];
export type OnHitEffects = {
  [k: string]: unknown;
}[];
export type OperationType = "attack_roll";
export type StatOverride = string | null;
export type ApplyConditionsOnFail = string[];
export type FailureDamage = DamageInstance[];
export type OperationType1 = "save";
export type SaveDcOverride = number | null;
export type SaveStat = string;
export type SuccessRule = "half_damage" | "no_damage";
export type AddStatModifier1 = boolean;
export type Amount = string | number | ResultReference;
export type OperationType2 = "heal";
export type RemovesConditions = string[];
export type StatUsed = string;
export type TempHp2 = boolean;
export type AllowSaveEnds = boolean;
export type AppliedConditionId = string;
export type DurationRounds = number;
export type OperationType3 = "effect_application";
export type RequiresConcentration = boolean;
export type Count = number;
export type ResourceType = string;
export type MaxTargets = number;
export type RadiusFeet = number | null;
export type RangeFeet = number;
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "TargetingType".
 */
export type TargetingType = "single" | "self" | "aoe_sphere" | "aoe_cone" | "line";
export type ActionOperationSpecs = ActionOperationSpec[];
export type ContentVersion = number;
export type Family = "ability";
export type Id9 = string;
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "LifecycleState".
 */
export type LifecycleState = "draft" | "published" | "archived" | "superseded";
export type Name16 = string;
export type PackId = string;
export type ModifierType = "flat";
export type StackGroup = string;
export type TargetStat = string;
export type Value3 = string | number | ResultReference;
export type ConditionGate = string | null;
export type DiceNotation = string;
export type ModifierType1 = "dice";
export type TargetStat1 = string;
export type ModifierType2 = "rule_override";
export type OverrideValue = string;
export type TargetStat2 = string;
export type PassiveEffects = (FlatModifierSpec | DiceModifierSpec | RuleOverrideModifierSpec)[];
export type ProvenanceAuthor = string | null;
export type ProvenanceSource = string;
export type ProvenanceUpdatedAt = string;
export type SchemaVersion = number;
export type Slug = string;
export type V05Abilities = AbilityDefinition[];
export type ContentVersion1 = number;
export type Family1 = "background";
export type Id10 = string;
export type Name17 = string;
export type PackId1 = string;
export type ProvenanceAuthor1 = string | null;
export type ProvenanceSource1 = string;
export type ProvenanceUpdatedAt1 = string;
export type SchemaVersion1 = number;
export type SkillProficiencies1 = string[];
export type Slug1 = string;
export type V05Backgrounds = BackgroundDefinition[];
export type ChainDepth = number;
export type HeadDefinitionId = string;
export type NextDefinitionId = string | null;
export type TerminalDefinitionId = string | null;
export type V05Chains = ReplacementChain[];
export type ContentVersion2 = number;
export type Family2 = "class";
export type HitDie1 = string;
export type Id11 = string;
export type Name18 = string;
export type PackId2 = string;
export type ProvenanceAuthor2 = string | null;
export type ProvenanceSource2 = string;
export type ProvenanceUpdatedAt2 = string;
export type SavingThrowProficiencies = string[];
export type SchemaVersion2 = number;
export type Slug2 = string;
export type V05Classes = ClassDefinition[];
export type ConditionType = "buff" | "debuff" | "status";
export type ContentVersion3 = number;
export type Family3 = "condition";
export type HasLevels = boolean;
export type Id12 = string;
export type ModifierSpecs = (FlatModifierSpec | DiceModifierSpec | RuleOverrideModifierSpec)[];
export type Name19 = string;
export type PackId3 = string;
export type ProvenanceAuthor3 = string | null;
export type ProvenanceSource3 = string;
export type ProvenanceUpdatedAt3 = string;
export type SchemaVersion3 = number;
export type Slug3 = string;
export type V05Conditions = ConditionDefinition[];
export type ActionOperationSpecs1 = ActionOperationSpec[];
export type ContentVersion4 = number;
export type Cost = number;
export type Family4 = "item";
export type Id13 = string;
export type ItemType = "weapon" | "armor" | "gear" | "consumable";
export type Name20 = string;
export type PackId4 = string;
export type ProvenanceAuthor4 = string | null;
export type ProvenanceSource4 = string;
export type ProvenanceUpdatedAt4 = string;
export type SchemaVersion4 = number;
export type Slug4 = string;
export type Weight2 = number;
export type V05Items = ItemDefinition[];
export type Id14 = string;
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "RelationKind".
 */
export type RelationKind = "inline_ref" | "prerequisite" | "replacement" | "parent_child" | "related" | "grants";
export type Required = boolean;
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ResolveMode".
 */
export type ResolveMode = "strict" | "best_effort";
export type SourceDefinitionId = string;
export type SourcePath = string;
export type TargetDefinitionId = string;
export type TargetFamily = string;
export type V05Links = LinkedEntryReference[];
export type ContentVersion5 = number;
export type Family5 = "lore";
export type Id15 = string;
export type LoreType = "faction" | "region" | "place" | "deity";
export type Name21 = string;
export type PackId5 = string;
export type ProvenanceAuthor5 = string | null;
export type ProvenanceSource5 = string;
export type ProvenanceUpdatedAt5 = string;
export type RichTextContent = string;
export type SchemaVersion5 = number;
export type Slug5 = string;
export type V05Lore = LoreDefinition[];
export type ActionOperationSpecs2 = ActionOperationSpec[];
export type ArmorClass4 = number;
export type ChallengeRating2 = number;
export type ContentVersion6 = number;
export type Family6 = "monster";
export type HitPointsFormula = string;
export type Id16 = string;
export type Name22 = string;
export type PackId6 = string;
export type ProvenanceAuthor6 = string | null;
export type ProvenanceSource6 = string;
export type ProvenanceUpdatedAt6 = string;
export type SchemaVersion6 = number;
export type Slug6 = string;
export type V05Monsters = MonsterDefinition[];
export type AuthorUserId = string | null;
export type CompatibilityTarget = string | null;
export type CreatedAt = string;
export type Id17 = string;
export type IsHomebrew = boolean;
export type PackKey = string | null;
export type PublishedVersion = number | null;
export type Title = string;
export type UpdatedAt = string;
export type V05Packs = ContentPackRecord[];
export type V05ResultAttributes = ResultAttribute[];
export type V05ResultReferences = ResultReference[];
export type ContentVersion7 = number;
export type Family7 = "species";
export type Id18 = string;
export type Name23 = string;
export type PackId7 = string;
export type ProvenanceAuthor7 = string | null;
export type ProvenanceSource7 = string;
export type ProvenanceUpdatedAt7 = string;
export type SchemaVersion7 = number;
export type Size3 = string;
export type Slug7 = string;
export type Speed5 = number;
export type V05Species = SpeciesDefinition[];
export type ActionOperationSpecs3 = ActionOperationSpec[];
export type CastingTime2 = string;
export type ContentVersion8 = number;
export type Family8 = "spell";
export type Id19 = string;
export type Level4 = number;
export type Name24 = string;
export type PackId8 = string;
export type ProvenanceAuthor8 = string | null;
export type ProvenanceSource8 = string;
export type ProvenanceUpdatedAt8 = string;
export type SchemaVersion8 = number;
export type School2 = string;
export type Slug8 = string;
export type V05Spells = SpellDefinition[];
export type V05ValueSources = (string | number | ResultReference)[];

export interface ExportModel {
  backgrounds: Backgrounds;
  campaign_context: CampaignContext;
  campaign_create: CampaignCreate;
  campaigns: Campaigns;
  character_create: CharacterCreate;
  characters: Characters1;
  classes: Classes;
  encounter_options: EncounterOptions;
  item_create: ItemCreate;
  items: Items;
  monster_create: MonsterCreate;
  monsters: Monsters;
  scene_options: SceneOptions;
  select_campaign_context_request: SelectCampaignContextRequest;
  species: Species;
  spell_create: SpellCreate;
  spells: Spells2;
  v05_abilities: V05Abilities;
  v05_backgrounds: V05Backgrounds;
  v05_chains: V05Chains;
  v05_classes: V05Classes;
  v05_conditions: V05Conditions;
  v05_items: V05Items;
  v05_links: V05Links;
  v05_lore: V05Lore;
  v05_monsters: V05Monsters;
  v05_packs: V05Packs;
  v05_result_attributes: V05ResultAttributes;
  v05_result_references: V05ResultReferences;
  v05_species: V05Species;
  v05_spells: V05Spells;
  v05_value_sources: V05ValueSources;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "BackgroundResponse".
 */
export interface BackgroundResponse {
  description: Description;
  effects?: Effects;
  equipment?: Equipment;
  feature?: Feature;
  id: Id;
  name: Name;
  skill_proficiencies?: SkillProficiencies;
  tool_proficiencies?: ToolProficiencies;
  [k: string]: unknown;
}
/**
 * Represents a dynamic effect in the game logic.
 * Example: {"trigger": "ON_EQUIP", "action": "ADD_AC", "value": 1}
 *
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "EffectConfig".
 */
export interface EffectConfig {
  action: Action;
  target?: Target;
  trigger: Trigger;
  value: Value;
  [k: string]: unknown;
}
export interface Value {
  [k: string]: unknown;
}
export interface Feature {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CampaignContextResponse".
 */
export interface CampaignContextResponse {
  campaign_id: CampaignId;
  context_version?: ContextVersion;
  encounter_id?: EncounterId;
  scene_id?: SceneId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CampaignCreate".
 */
export interface CampaignCreate1 {
  description?: Description1;
  dm_id?: DmId;
  name: Name1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CampaignResponse".
 */
export interface CampaignResponse {
  active_encounter_id?: ActiveEncounterId;
  characters?: Characters;
  context_version?: ContextVersion1;
  current_scene?: CurrentScene;
  description?: Description6;
  dm_id?: DmId1;
  id: Id6;
  name: Name7;
  role?: Role;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CharacterResponse".
 */
export interface CharacterResponse {
  ability_ids?: AbilityIds;
  actions?: Actions;
  alignment?: Alignment;
  armor_class?: ArmorClass;
  background?: BackgroundResponse | null;
  background_id?: BackgroundId;
  campaign_id?: CampaignId1;
  char_class?: ClassResponse | null;
  charisma?: Charisma;
  class_id: ClassId;
  constitution?: Constitution;
  current_hp: CurrentHp;
  dexterity?: Dexterity;
  effects?: Effects2;
  hit_dice: HitDice;
  id: Id2;
  initiative?: Initiative;
  intelligence?: Intelligence;
  inventory?: Inventory;
  level?: Level;
  max_hp: MaxHp;
  name: Name5;
  player_id?: PlayerId;
  player_name?: PlayerName;
  species?: SpeciesResponse | null;
  species_id: SpeciesId;
  speed?: Speed1;
  spell_slots?: SpellSlots;
  spells?: Spells;
  status?: Status;
  strength?: Strength;
  temp_hp?: TempHp;
  wisdom?: Wisdom;
  xp?: Xp;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ClassResponse".
 */
export interface ClassResponse {
  description: Description2;
  effects?: Effects1;
  hit_die: HitDie;
  id: Id1;
  name: Name2;
  proficiencies?: Proficiencies;
  progression?: Progression;
  saving_throws?: SavingThrows;
  [k: string]: unknown;
}
export interface Proficiencies {
  [k: string]: unknown;
}
/**
 * Represents a modifier or rule change applied to a game entity.
 * V1 Focus: Static Modifiers.
 *
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "Effect".
 */
export interface Effect {
  description?: Description3;
  name: Name3;
  source?: Source;
  target: Target1;
  type: Type;
  value: Value1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemInstance".
 */
export interface ItemInstance {
  attuned?: Attuned;
  current_charges?: CurrentCharges;
  custom_name?: CustomName;
  equipped?: Equipped;
  id: Id3;
  item_id: ItemId;
  quantity?: Quantity;
  template?: ItemResponse | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemResponse".
 */
export interface ItemResponse {
  description?: Description4;
  effects?: Effects3;
  id: Id4;
  name: Name4;
  price?: Price;
  properties?: Properties;
  rarity: Rarity;
  type: Type1;
  weight?: Weight;
  [k: string]: unknown;
}
export interface Properties {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpeciesResponse".
 */
export interface SpeciesResponse {
  ability_bonuses?: AbilityBonuses;
  description: Description5;
  effects?: Effects4;
  id: Id5;
  languages?: Languages;
  name: Name6;
  size?: Size;
  speed?: Speed;
  traits?: Traits;
  [k: string]: unknown;
}
export interface AbilityBonuses {
  [k: string]: number;
}
export interface SpellSlots {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CharacterCreate".
 */
export interface CharacterCreate1 {
  ability_ids?: AbilityIds1;
  actions?: Actions1;
  alignment?: Alignment1;
  armor_class?: ArmorClass1;
  background_id?: BackgroundId1;
  campaign_id?: CampaignId2;
  charisma?: Charisma1;
  class_id: ClassId1;
  constitution?: Constitution1;
  current_hp: CurrentHp1;
  dexterity?: Dexterity1;
  effects?: Effects5;
  hit_dice: HitDice1;
  initiative?: Initiative1;
  intelligence?: Intelligence1;
  inventory?: Inventory1;
  level?: Level1;
  max_hp: MaxHp1;
  name: Name8;
  player_id?: PlayerId1;
  player_name?: PlayerName1;
  species_id: SpeciesId1;
  speed?: Speed2;
  spell_slots?: SpellSlots1;
  spells?: Spells1;
  status?: Status1;
  strength?: Strength1;
  temp_hp?: TempHp1;
  wisdom?: Wisdom1;
  xp?: Xp1;
  [k: string]: unknown;
}
export interface SpellSlots1 {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "EncounterOptionResponse".
 */
export interface EncounterOptionResponse {
  encounter_id: EncounterId1;
  name: Name9;
  scene_id: SceneId1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemCreate".
 */
export interface ItemCreate1 {
  description?: Description7;
  effects?: Effects6;
  name: Name10;
  price?: Price1;
  properties?: Properties1;
  rarity: Rarity1;
  type: Type2;
  weight?: Weight1;
  [k: string]: unknown;
}
export interface Properties1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "MonsterCreate".
 */
export interface MonsterCreate1 {
  actions?: Actions2;
  alignment: Alignment2;
  armor_class: ArmorClass2;
  challenge_rating: ChallengeRating;
  charisma: Charisma2;
  constitution: Constitution2;
  description?: Description8;
  dexterity: Dexterity2;
  effects?: Effects7;
  hit_dice: HitDice2;
  hit_points: HitPoints;
  intelligence: Intelligence2;
  inventory?: Inventory2;
  languages: Languages1;
  legendary_actions?: LegendaryActions;
  name: Name11;
  proficiencies?: Proficiencies1;
  senses?: Senses;
  size: Size1;
  special_abilities?: SpecialAbilities;
  speed: Speed3;
  strength: Strength2;
  type: Type3;
  wisdom: Wisdom2;
  xp: Xp2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "MonsterActionRef".
 */
export interface MonsterActionRef {
  action_id: ActionId;
  display_name?: DisplayName;
}
export interface Senses {
  [k: string]: unknown;
}
export interface Speed3 {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "MonsterResponse".
 */
export interface MonsterResponse {
  actions?: Actions3;
  alignment: Alignment3;
  armor_class: ArmorClass3;
  challenge_rating: ChallengeRating1;
  charisma: Charisma3;
  constitution: Constitution3;
  description?: Description9;
  dexterity: Dexterity3;
  effects?: Effects8;
  hit_dice: HitDice3;
  hit_points: HitPoints1;
  id: Id7;
  intelligence: Intelligence3;
  inventory?: Inventory3;
  languages: Languages2;
  legendary_actions?: LegendaryActions1;
  name: Name12;
  proficiencies?: Proficiencies2;
  senses?: Senses1;
  size: Size2;
  special_abilities?: SpecialAbilities1;
  speed: Speed4;
  strength: Strength3;
  type: Type4;
  wisdom: Wisdom3;
  xp: Xp3;
  [k: string]: unknown;
}
export interface Senses1 {
  [k: string]: unknown;
}
export interface Speed4 {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SceneOptionResponse".
 */
export interface SceneOptionResponse {
  name: Name13;
  scene_id: SceneId2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SelectCampaignContextRequest".
 */
export interface SelectCampaignContextRequest1 {
  encounter_id: EncounterId2;
  scene_id: SceneId3;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpellCreate".
 */
export interface SpellCreate1 {
  casting_time: CastingTime;
  components?: Components;
  description?: Description10;
  duration: Duration;
  effects?: Effects9;
  level: Level2;
  name: Name14;
  range: Range;
  school: School;
  [k: string]: unknown;
}
export interface Components {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpellResponse".
 */
export interface SpellResponse {
  casting_time: CastingTime1;
  components?: Components1;
  description?: Description11;
  duration: Duration1;
  effects?: Effects10;
  id: Id8;
  level: Level3;
  name: Name15;
  range: Range1;
  school: School1;
  [k: string]: unknown;
}
export interface Components1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "AbilityDefinition".
 */
export interface AbilityDefinition {
  ability_type: AbilityType;
  action_operation_specs: ActionOperationSpecs;
  content_version: ContentVersion;
  family?: Family;
  id: Id9;
  lifecycle_state: LifecycleState;
  name: Name16;
  pack_id: PackId;
  passive_effects: PassiveEffects;
  provenance_author?: ProvenanceAuthor;
  provenance_source: ProvenanceSource;
  provenance_updated_at: ProvenanceUpdatedAt;
  schema_version: SchemaVersion;
  slug: Slug;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ActionOperationSpec".
 */
export interface ActionOperationSpec {
  activation_cost: ActivationCost;
  activation_trigger?: ActivationTrigger;
  operation_id: OperationId;
  payload: Payload;
  resource_consumption?: ResourceConsumption | null;
  targeting_spec: TargetingSpec;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "AttackRollPayload".
 */
export interface AttackRollPayload {
  attack_type: AttackType;
  critical_threshold?: CriticalThreshold;
  damage_instances: DamageInstances;
  on_hit_effects?: OnHitEffects;
  operation_type?: OperationType;
  stat_override?: StatOverride;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "DamageInstance".
 */
export interface DamageInstance {
  add_stat_modifier: AddStatModifier;
  damage_type: DamageType;
  value: Value2;
  [k: string]: unknown;
}
/**
 * A pointer from a consumer operation to a source operation's result.
 *
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ResultReference".
 */
export interface ResultReference {
  attribute: ResultAttribute;
  bonus?: Bonus;
  multiplier?: Multiplier;
  source_operation_id: SourceOperationId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SavePayload".
 */
export interface SavePayload {
  apply_conditions_on_fail?: ApplyConditionsOnFail;
  failure_damage: FailureDamage;
  operation_type?: OperationType1;
  save_dc_override?: SaveDcOverride;
  save_stat: SaveStat;
  success_rule: SuccessRule;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "HealPayload".
 */
export interface HealPayload {
  add_stat_modifier: AddStatModifier1;
  amount: Amount;
  operation_type?: OperationType2;
  removes_conditions?: RemovesConditions;
  stat_used: StatUsed;
  temp_hp: TempHp2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "EffectApplicationPayload".
 */
export interface EffectApplicationPayload {
  allow_save_ends: AllowSaveEnds;
  applied_condition_id: AppliedConditionId;
  duration_rounds: DurationRounds;
  operation_type?: OperationType3;
  requires_concentration: RequiresConcentration;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ResourceConsumption".
 */
export interface ResourceConsumption {
  count: Count;
  resource_type: ResourceType;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "TargetingSpec".
 */
export interface TargetingSpec {
  max_targets: MaxTargets;
  radius_feet?: RadiusFeet;
  range_feet: RangeFeet;
  type: TargetingType;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "FlatModifierSpec".
 */
export interface FlatModifierSpec {
  modifier_type?: ModifierType;
  stack_group: StackGroup;
  target_stat: TargetStat;
  value: Value3;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "DiceModifierSpec".
 */
export interface DiceModifierSpec {
  condition_gate?: ConditionGate;
  dice_notation: DiceNotation;
  modifier_type?: ModifierType1;
  target_stat: TargetStat1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "RuleOverrideModifierSpec".
 */
export interface RuleOverrideModifierSpec {
  modifier_type?: ModifierType2;
  override_value: OverrideValue;
  target_stat: TargetStat2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "BackgroundDefinition".
 */
export interface BackgroundDefinition {
  content_version: ContentVersion1;
  family?: Family1;
  id: Id10;
  lifecycle_state: LifecycleState;
  name: Name17;
  pack_id: PackId1;
  provenance_author?: ProvenanceAuthor1;
  provenance_source: ProvenanceSource1;
  provenance_updated_at: ProvenanceUpdatedAt1;
  schema_version: SchemaVersion1;
  skill_proficiencies: SkillProficiencies1;
  slug: Slug1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ReplacementChain".
 */
export interface ReplacementChain {
  chain_depth: ChainDepth;
  head_definition_id: HeadDefinitionId;
  next_definition_id?: NextDefinitionId;
  terminal_definition_id?: TerminalDefinitionId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ClassDefinition".
 */
export interface ClassDefinition {
  content_version: ContentVersion2;
  family?: Family2;
  hit_die: HitDie1;
  id: Id11;
  lifecycle_state: LifecycleState;
  name: Name18;
  pack_id: PackId2;
  provenance_author?: ProvenanceAuthor2;
  provenance_source: ProvenanceSource2;
  provenance_updated_at: ProvenanceUpdatedAt2;
  saving_throw_proficiencies: SavingThrowProficiencies;
  schema_version: SchemaVersion2;
  slug: Slug2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ConditionDefinition".
 */
export interface ConditionDefinition {
  condition_type: ConditionType;
  content_version: ContentVersion3;
  family?: Family3;
  has_levels: HasLevels;
  id: Id12;
  lifecycle_state: LifecycleState;
  modifier_specs: ModifierSpecs;
  name: Name19;
  pack_id: PackId3;
  provenance_author?: ProvenanceAuthor3;
  provenance_source: ProvenanceSource3;
  provenance_updated_at: ProvenanceUpdatedAt3;
  schema_version: SchemaVersion3;
  slug: Slug3;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemDefinition".
 */
export interface ItemDefinition {
  action_operation_specs: ActionOperationSpecs1;
  content_version: ContentVersion4;
  cost: Cost;
  family?: Family4;
  id: Id13;
  item_type: ItemType;
  lifecycle_state: LifecycleState;
  name: Name20;
  pack_id: PackId4;
  provenance_author?: ProvenanceAuthor4;
  provenance_source: ProvenanceSource4;
  provenance_updated_at: ProvenanceUpdatedAt4;
  schema_version: SchemaVersion4;
  slug: Slug4;
  weight: Weight2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "LinkedEntryReference".
 */
export interface LinkedEntryReference {
  id: Id14;
  relation_kind: RelationKind;
  required: Required;
  resolve_mode: ResolveMode;
  source_definition_id: SourceDefinitionId;
  source_path: SourcePath;
  target_definition_id: TargetDefinitionId;
  target_family: TargetFamily;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "LoreDefinition".
 */
export interface LoreDefinition {
  content_version: ContentVersion5;
  family?: Family5;
  id: Id15;
  lifecycle_state: LifecycleState;
  lore_type: LoreType;
  name: Name21;
  pack_id: PackId5;
  provenance_author?: ProvenanceAuthor5;
  provenance_source: ProvenanceSource5;
  provenance_updated_at: ProvenanceUpdatedAt5;
  rich_text_content: RichTextContent;
  schema_version: SchemaVersion5;
  slug: Slug5;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "MonsterDefinition".
 */
export interface MonsterDefinition {
  action_operation_specs: ActionOperationSpecs2;
  armor_class: ArmorClass4;
  challenge_rating: ChallengeRating2;
  content_version: ContentVersion6;
  family?: Family6;
  hit_points_formula: HitPointsFormula;
  id: Id16;
  lifecycle_state: LifecycleState;
  name: Name22;
  pack_id: PackId6;
  provenance_author?: ProvenanceAuthor6;
  provenance_source: ProvenanceSource6;
  provenance_updated_at: ProvenanceUpdatedAt6;
  schema_version: SchemaVersion6;
  slug: Slug6;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ContentPackRecord".
 */
export interface ContentPackRecord {
  author_user_id?: AuthorUserId;
  compatibility_target?: CompatibilityTarget;
  created_at: CreatedAt;
  id: Id17;
  is_homebrew: IsHomebrew;
  lifecycle_state: LifecycleState;
  pack_key?: PackKey;
  published_version?: PublishedVersion;
  title: Title;
  updated_at: UpdatedAt;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpeciesDefinition".
 */
export interface SpeciesDefinition {
  content_version: ContentVersion7;
  family?: Family7;
  id: Id18;
  lifecycle_state: LifecycleState;
  name: Name23;
  pack_id: PackId7;
  provenance_author?: ProvenanceAuthor7;
  provenance_source: ProvenanceSource7;
  provenance_updated_at: ProvenanceUpdatedAt7;
  schema_version: SchemaVersion7;
  size: Size3;
  slug: Slug7;
  speed: Speed5;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpellDefinition".
 */
export interface SpellDefinition {
  action_operation_specs: ActionOperationSpecs3;
  casting_time: CastingTime2;
  content_version: ContentVersion8;
  family?: Family8;
  id: Id19;
  level: Level4;
  lifecycle_state: LifecycleState;
  name: Name24;
  pack_id: PackId8;
  provenance_author?: ProvenanceAuthor8;
  provenance_source: ProvenanceSource8;
  provenance_updated_at: ProvenanceUpdatedAt8;
  schema_version: SchemaVersion8;
  school: School2;
  slug: Slug8;
  [k: string]: unknown;
}
