/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Description = string | null;
export type Name1 = string;
export type Description1 = string | null;
export type Type = "BONUS" | "SET";
export type Target = string;
export type Value = number;
export type Source = string | null;
export type Effects = Effect[];
export type Type1 = string;
export type Rarity = string;
export type Weight = number;
export type Price = number;
export type Id = string;
export type Items = ItemResponse[];
export type Name2 = string;
export type Description2 = string | null;
export type Trigger = string;
export type Action = string;
export type Target1 = string | null;
export type Effects1 = EffectConfig[];
export type Level = number;
export type School = string;
export type CastingTime = string;
export type Range = string;
export type Duration = string;
export type Id1 = string;
export type Spells = SpellResponse[];
export type Name3 = string;
export type Description3 = string | null;
export type Effects2 = Effect[];
export type Size = string;
export type Type2 = string;
export type Alignment = string;
export type ArmorClass = number;
export type HitPoints = number;
export type HitDice = string;
export type Strength = number;
export type Dexterity = number;
export type Constitution = number;
export type Intelligence = number;
export type Wisdom = number;
export type Charisma = number;
export type Proficiencies = {
  [k: string]: unknown;
}[];
export type Languages = string;
export type ChallengeRating = number;
export type Xp = number;
export type SpecialAbilities = {
  [k: string]: unknown;
}[];
export type Actions = {
  [k: string]: unknown;
}[];
export type LegendaryActions = {
  [k: string]: unknown;
}[];
export type Inventory = {
  [k: string]: unknown;
}[];
export type Id2 = string;
export type Monsters = MonsterResponse[];
export type Name4 = string;
export type Description4 = string | null;
export type DmId = string | null;
export type Id3 = string;
export type Name5 = string;
export type PlayerName = string | null;
export type CampaignId = string | null;
export type SpeciesId = string;
export type ClassId = string;
export type BackgroundId = string | null;
export type Level1 = number;
export type Xp1 = number;
export type Alignment1 = string | null;
export type Strength1 = number;
export type Dexterity1 = number;
export type Constitution1 = number;
export type Intelligence1 = number;
export type Wisdom1 = number;
export type Charisma1 = number;
export type MaxHp = number;
export type CurrentHp = number;
export type TempHp = number;
export type HitDice1 = string;
export type ArmorClass1 = number;
export type Speed1 = number;
export type Initiative = number;
export type Id4 = string;
export type ItemId = string;
export type Quantity = number;
export type Equipped = boolean;
export type Attuned = boolean;
export type CustomName = string | null;
export type CurrentCharges = number | null;
export type Inventory1 = ItemInstance[];
export type Spells1 = {
  [k: string]: unknown;
}[];
export type Actions1 = {
  [k: string]: unknown;
}[];
export type Effects3 = Effect[];
export type Id5 = string;
export type Characters = CharacterResponse[];
export type Campaigns = CampaignResponse[];
export type Characters1 = CharacterResponse[];
export type Name6 = string;
export type Description5 = string;
export type Effects4 = EffectConfig[];
export type Speed2 = number;
export type Size1 = string;
export type Traits = {
  [k: string]: unknown;
}[];
export type Languages1 = string[];
export type Id6 = string;
export type Species1 = SpeciesResponse[];
export type Name7 = string;
export type Description6 = string;
export type Effects5 = EffectConfig[];
export type HitDie = string;
export type SavingThrows = string[];
export type Progression = {
  [k: string]: unknown;
}[];
export type Id7 = string;
export type Classes = ClassResponse[];
export type Name8 = string;
export type Description7 = string;
export type Effects6 = EffectConfig[];
export type SkillProficiencies = string[];
export type ToolProficiencies = string[];
export type Equipment = string[];
export type Id8 = string;
export type Backgrounds = BackgroundResponse[];

export interface ExportModel {
  items: Items;
  spells: Spells;
  monsters: Monsters;
  campaigns: Campaigns;
  characters: Characters1;
  species: Species1;
  classes: Classes;
  backgrounds: Backgrounds;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemResponse".
 */
export interface ItemResponse {
  name: Name;
  description?: Description;
  effects?: Effects;
  type: Type1;
  rarity: Rarity;
  weight?: Weight;
  price?: Price;
  properties?: Properties;
  id: Id;
  [k: string]: unknown;
}
/**
 * Represents a modifier or rule change applied to a game entity.
 * V1 Focus: Static Modifiers.
 *
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "Effect".
 */
export interface Effect {
  name: Name1;
  description?: Description1;
  type: Type;
  target: Target;
  value: Value;
  source?: Source;
  [k: string]: unknown;
}
export interface Properties {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpellResponse".
 */
export interface SpellResponse {
  name: Name2;
  description?: Description2;
  effects?: Effects1;
  level: Level;
  school: School;
  casting_time: CastingTime;
  range: Range;
  components?: Components;
  duration: Duration;
  id: Id1;
  [k: string]: unknown;
}
/**
 * Represents a dynamic effect in the game logic.
 * Example: {"trigger": "ON_EQUIP", "action": "ADD_AC", "value": 1}
 *
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "EffectConfig".
 */
export interface EffectConfig {
  trigger: Trigger;
  action: Action;
  value: Value1;
  target?: Target1;
  [k: string]: unknown;
}
export interface Value1 {
  [k: string]: unknown;
}
export interface Components {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "MonsterResponse".
 */
export interface MonsterResponse {
  name: Name3;
  description?: Description3;
  effects?: Effects2;
  size: Size;
  type: Type2;
  alignment: Alignment;
  armor_class: ArmorClass;
  hit_points: HitPoints;
  hit_dice: HitDice;
  speed: Speed;
  strength: Strength;
  dexterity: Dexterity;
  constitution: Constitution;
  intelligence: Intelligence;
  wisdom: Wisdom;
  charisma: Charisma;
  proficiencies?: Proficiencies;
  senses?: Senses;
  languages: Languages;
  challenge_rating: ChallengeRating;
  xp: Xp;
  special_abilities?: SpecialAbilities;
  actions?: Actions;
  legendary_actions?: LegendaryActions;
  inventory?: Inventory;
  id: Id2;
  [k: string]: unknown;
}
export interface Speed {
  [k: string]: number;
}
export interface Senses {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CampaignResponse".
 */
export interface CampaignResponse {
  name: Name4;
  description?: Description4;
  dm_id?: DmId;
  id: Id3;
  characters?: Characters;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CharacterResponse".
 */
export interface CharacterResponse {
  name: Name5;
  player_name?: PlayerName;
  campaign_id?: CampaignId;
  species_id: SpeciesId;
  class_id: ClassId;
  background_id?: BackgroundId;
  level?: Level1;
  xp?: Xp1;
  alignment?: Alignment1;
  strength?: Strength1;
  dexterity?: Dexterity1;
  constitution?: Constitution1;
  intelligence?: Intelligence1;
  wisdom?: Wisdom1;
  charisma?: Charisma1;
  max_hp: MaxHp;
  current_hp: CurrentHp;
  temp_hp?: TempHp;
  hit_dice: HitDice1;
  armor_class?: ArmorClass1;
  speed?: Speed1;
  initiative?: Initiative;
  inventory?: Inventory1;
  spells?: Spells1;
  spell_slots?: SpellSlots;
  actions?: Actions1;
  effects?: Effects3;
  id: Id5;
  species?: unknown;
  char_class?: unknown;
  background?: unknown;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemInstance".
 */
export interface ItemInstance {
  id: Id4;
  item_id: ItemId;
  template?: ItemResponse | null;
  quantity?: Quantity;
  equipped?: Equipped;
  attuned?: Attuned;
  custom_name?: CustomName;
  current_charges?: CurrentCharges;
  [k: string]: unknown;
}
export interface SpellSlots {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpeciesResponse".
 */
export interface SpeciesResponse {
  name: Name6;
  description: Description5;
  effects?: Effects4;
  speed?: Speed2;
  size?: Size1;
  ability_bonuses?: AbilityBonuses;
  traits?: Traits;
  languages?: Languages1;
  id: Id6;
  [k: string]: unknown;
}
export interface AbilityBonuses {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ClassResponse".
 */
export interface ClassResponse {
  name: Name7;
  description: Description6;
  effects?: Effects5;
  hit_die: HitDie;
  proficiencies?: Proficiencies1;
  saving_throws?: SavingThrows;
  progression?: Progression;
  id: Id7;
  [k: string]: unknown;
}
export interface Proficiencies1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "BackgroundResponse".
 */
export interface BackgroundResponse {
  name: Name8;
  description: Description7;
  effects?: Effects6;
  skill_proficiencies?: SkillProficiencies;
  tool_proficiencies?: ToolProficiencies;
  equipment?: Equipment;
  feature?: Feature;
  id: Id8;
  [k: string]: unknown;
}
export interface Feature {
  [k: string]: unknown;
}
