/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Description = string;
export type Action = string;
export type Target = string | null;
export type Trigger = string;
export type Effects = EffectConfig[];
export type Equipment = string[];
export type Id = string;
export type Name = string;
export type SkillProficiencies = string[];
export type ToolProficiencies = string[];
export type Backgrounds = BackgroundResponse[];
export type CampaignId = string;
export type ContextVersion = number;
export type EncounterId = string | null;
export type SceneId = string | null;
export type CampaignContext = CampaignContextResponse[];
export type Description1 = string | null;
export type DmId = string | null;
export type Name1 = string;
export type CampaignCreate = CampaignCreate1[];
export type ActiveEncounterId = string | null;
export type Actions = {
  [k: string]: unknown;
}[];
export type Alignment = string | null;
export type ArmorClass = number;
export type BackgroundId = string | null;
export type CampaignId1 = string | null;
export type Description2 = string;
export type Effects1 = EffectConfig[];
export type HitDie = string;
export type Id1 = string;
export type Name2 = string;
export type Progression = {
  [k: string]: unknown;
}[];
export type SavingThrows = string[];
export type Charisma = number;
export type ClassId = string;
export type Constitution = number;
export type CurrentHp = number;
export type Dexterity = number;
export type Description3 = string | null;
export type Name3 = string;
export type Source = string | null;
export type Target1 = string;
export type Type = "BONUS" | "SET";
export type Value1 = number;
export type Effects2 = Effect[];
export type HitDice = string;
export type Id2 = string;
export type Initiative = number;
export type Intelligence = number;
export type Attuned = boolean;
export type CurrentCharges = number | null;
export type CustomName = string | null;
export type Equipped = boolean;
export type Id3 = string;
export type ItemId = string;
export type Quantity = number;
export type Description4 = string | null;
export type Effects3 = Effect[];
export type Id4 = string;
export type Name4 = string;
export type Price = number;
export type Rarity = string;
export type Type1 = string;
export type Weight = number;
export type Inventory = ItemInstance[];
export type Level = number;
export type MaxHp = number;
export type Name5 = string;
export type PlayerName = string | null;
export type Description5 = string;
export type Effects4 = EffectConfig[];
export type Id5 = string;
export type Languages = string[];
export type Name6 = string;
export type Size = string;
export type Speed = number;
export type Traits = {
  [k: string]: unknown;
}[];
export type SpeciesId = string;
export type Speed1 = number;
export type Spells = {
  [k: string]: unknown;
}[];
export type Strength = number;
export type TempHp = number;
export type Wisdom = number;
export type Xp = number;
export type Characters = CharacterResponse[];
export type ContextVersion1 = number;
export type CurrentScene = string | null;
export type Description6 = string | null;
export type DmId1 = string | null;
export type Id6 = string;
export type Name7 = string;
export type Role = string | null;
export type Campaigns = CampaignResponse[];
export type Actions1 = {
  [k: string]: unknown;
}[];
export type Alignment1 = string | null;
export type ArmorClass1 = number;
export type BackgroundId1 = string | null;
export type CampaignId2 = string | null;
export type Charisma1 = number;
export type ClassId1 = string;
export type Constitution1 = number;
export type CurrentHp1 = number;
export type Dexterity1 = number;
export type Effects5 = Effect[];
export type HitDice1 = string;
export type Initiative1 = number;
export type Intelligence1 = number;
export type Inventory1 = ItemInstance[];
export type Level1 = number;
export type MaxHp1 = number;
export type Name8 = string;
export type PlayerName1 = string | null;
export type SpeciesId1 = string;
export type Speed2 = number;
export type Spells1 = {
  [k: string]: unknown;
}[];
export type Strength1 = number;
export type TempHp1 = number;
export type Wisdom1 = number;
export type Xp1 = number;
export type CharacterCreate = CharacterCreate1[];
export type Characters1 = CharacterResponse[];
export type Classes = ClassResponse[];
export type EncounterId1 = string;
export type Name9 = string;
export type SceneId1 = string;
export type EncounterOptions = EncounterOptionResponse[];
export type Description7 = string | null;
export type Effects6 = Effect[];
export type Name10 = string;
export type Price1 = number;
export type Rarity1 = string;
export type Type2 = string;
export type Weight1 = number;
export type ItemCreate = ItemCreate1[];
export type Items = ItemResponse[];
export type ActionId = string;
export type DisplayName = string | null;
export type Actions2 = MonsterActionRef[];
export type Alignment2 = string;
export type ArmorClass2 = number;
export type ChallengeRating = number;
export type Charisma2 = number;
export type Constitution2 = number;
export type Description8 = string | null;
export type Dexterity2 = number;
export type Effects7 = Effect[];
export type HitDice2 = string;
export type HitPoints = number;
export type Intelligence2 = number;
export type Inventory2 = {
  [k: string]: unknown;
}[];
export type Languages1 = string;
export type LegendaryActions = {
  [k: string]: unknown;
}[];
export type Name11 = string;
export type Proficiencies1 = {
  [k: string]: unknown;
}[];
export type Size1 = string;
export type SpecialAbilities = {
  [k: string]: unknown;
}[];
export type Strength2 = number;
export type Type3 = string;
export type Wisdom2 = number;
export type Xp2 = number;
export type MonsterCreate = MonsterCreate1[];
export type Actions3 = MonsterActionRef[];
export type Alignment3 = string;
export type ArmorClass3 = number;
export type ChallengeRating1 = number;
export type Charisma3 = number;
export type Constitution3 = number;
export type Description9 = string | null;
export type Dexterity3 = number;
export type Effects8 = Effect[];
export type HitDice3 = string;
export type HitPoints1 = number;
export type Id7 = string;
export type Intelligence3 = number;
export type Inventory3 = {
  [k: string]: unknown;
}[];
export type Languages2 = string;
export type LegendaryActions1 = {
  [k: string]: unknown;
}[];
export type Name12 = string;
export type Proficiencies2 = {
  [k: string]: unknown;
}[];
export type Size2 = string;
export type SpecialAbilities1 = {
  [k: string]: unknown;
}[];
export type Strength3 = number;
export type Type4 = string;
export type Wisdom3 = number;
export type Xp3 = number;
export type Monsters = MonsterResponse[];
export type Name13 = string;
export type SceneId2 = string;
export type SceneOptions = SceneOptionResponse[];
export type EncounterId2 = string;
export type SceneId3 = string;
export type SelectCampaignContextRequest = SelectCampaignContextRequest1[];
export type Species = SpeciesResponse[];
export type CastingTime = string;
export type Description10 = string | null;
export type Duration = string;
export type Effects9 = EffectConfig[];
export type Level2 = number;
export type Name14 = string;
export type Range = string;
export type School = string;
export type SpellCreate = SpellCreate1[];
export type CastingTime1 = string;
export type Description11 = string | null;
export type Duration1 = string;
export type Effects10 = EffectConfig[];
export type Id8 = string;
export type Level3 = number;
export type Name15 = string;
export type Range1 = string;
export type School1 = string;
export type Spells2 = SpellResponse[];

export interface ExportModel {
  backgrounds: Backgrounds;
  campaign_context: CampaignContext;
  campaign_create: CampaignCreate;
  campaigns: Campaigns;
  character_create: CharacterCreate;
  characters: Characters1;
  classes: Classes;
  encounter_options: EncounterOptions;
  item_create: ItemCreate;
  items: Items;
  monster_create: MonsterCreate;
  monsters: Monsters;
  scene_options: SceneOptions;
  select_campaign_context_request: SelectCampaignContextRequest;
  species: Species;
  spell_create: SpellCreate;
  spells: Spells2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "BackgroundResponse".
 */
export interface BackgroundResponse {
  description: Description;
  effects?: Effects;
  equipment?: Equipment;
  feature?: Feature;
  id: Id;
  name: Name;
  skill_proficiencies?: SkillProficiencies;
  tool_proficiencies?: ToolProficiencies;
  [k: string]: unknown;
}
/**
 * Represents a dynamic effect in the game logic.
 * Example: {"trigger": "ON_EQUIP", "action": "ADD_AC", "value": 1}
 *
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "EffectConfig".
 */
export interface EffectConfig {
  action: Action;
  target?: Target;
  trigger: Trigger;
  value: Value;
  [k: string]: unknown;
}
export interface Value {
  [k: string]: unknown;
}
export interface Feature {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CampaignContextResponse".
 */
export interface CampaignContextResponse {
  campaign_id: CampaignId;
  context_version?: ContextVersion;
  encounter_id?: EncounterId;
  scene_id?: SceneId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CampaignCreate".
 */
export interface CampaignCreate1 {
  description?: Description1;
  dm_id?: DmId;
  name: Name1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CampaignResponse".
 */
export interface CampaignResponse {
  active_encounter_id?: ActiveEncounterId;
  characters?: Characters;
  context_version?: ContextVersion1;
  current_scene?: CurrentScene;
  description?: Description6;
  dm_id?: DmId1;
  id: Id6;
  name: Name7;
  role?: Role;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CharacterResponse".
 */
export interface CharacterResponse {
  actions?: Actions;
  alignment?: Alignment;
  armor_class?: ArmorClass;
  background?: BackgroundResponse | null;
  background_id?: BackgroundId;
  campaign_id?: CampaignId1;
  char_class?: ClassResponse | null;
  charisma?: Charisma;
  class_id: ClassId;
  constitution?: Constitution;
  current_hp: CurrentHp;
  dexterity?: Dexterity;
  effects?: Effects2;
  hit_dice: HitDice;
  id: Id2;
  initiative?: Initiative;
  intelligence?: Intelligence;
  inventory?: Inventory;
  level?: Level;
  max_hp: MaxHp;
  name: Name5;
  player_name?: PlayerName;
  species?: SpeciesResponse | null;
  species_id: SpeciesId;
  speed?: Speed1;
  spell_slots?: SpellSlots;
  spells?: Spells;
  strength?: Strength;
  temp_hp?: TempHp;
  wisdom?: Wisdom;
  xp?: Xp;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ClassResponse".
 */
export interface ClassResponse {
  description: Description2;
  effects?: Effects1;
  hit_die: HitDie;
  id: Id1;
  name: Name2;
  proficiencies?: Proficiencies;
  progression?: Progression;
  saving_throws?: SavingThrows;
  [k: string]: unknown;
}
export interface Proficiencies {
  [k: string]: unknown;
}
/**
 * Represents a modifier or rule change applied to a game entity.
 * V1 Focus: Static Modifiers.
 *
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "Effect".
 */
export interface Effect {
  description?: Description3;
  name: Name3;
  source?: Source;
  target: Target1;
  type: Type;
  value: Value1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemInstance".
 */
export interface ItemInstance {
  attuned?: Attuned;
  current_charges?: CurrentCharges;
  custom_name?: CustomName;
  equipped?: Equipped;
  id: Id3;
  item_id: ItemId;
  quantity?: Quantity;
  template?: ItemResponse | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemResponse".
 */
export interface ItemResponse {
  description?: Description4;
  effects?: Effects3;
  id: Id4;
  name: Name4;
  price?: Price;
  properties?: Properties;
  rarity: Rarity;
  type: Type1;
  weight?: Weight;
  [k: string]: unknown;
}
export interface Properties {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpeciesResponse".
 */
export interface SpeciesResponse {
  ability_bonuses?: AbilityBonuses;
  description: Description5;
  effects?: Effects4;
  id: Id5;
  languages?: Languages;
  name: Name6;
  size?: Size;
  speed?: Speed;
  traits?: Traits;
  [k: string]: unknown;
}
export interface AbilityBonuses {
  [k: string]: number;
}
export interface SpellSlots {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "CharacterCreate".
 */
export interface CharacterCreate1 {
  actions?: Actions1;
  alignment?: Alignment1;
  armor_class?: ArmorClass1;
  background_id?: BackgroundId1;
  campaign_id?: CampaignId2;
  charisma?: Charisma1;
  class_id: ClassId1;
  constitution?: Constitution1;
  current_hp: CurrentHp1;
  dexterity?: Dexterity1;
  effects?: Effects5;
  hit_dice: HitDice1;
  initiative?: Initiative1;
  intelligence?: Intelligence1;
  inventory?: Inventory1;
  level?: Level1;
  max_hp: MaxHp1;
  name: Name8;
  player_name?: PlayerName1;
  species_id: SpeciesId1;
  speed?: Speed2;
  spell_slots?: SpellSlots1;
  spells?: Spells1;
  strength?: Strength1;
  temp_hp?: TempHp1;
  wisdom?: Wisdom1;
  xp?: Xp1;
  [k: string]: unknown;
}
export interface SpellSlots1 {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "EncounterOptionResponse".
 */
export interface EncounterOptionResponse {
  encounter_id: EncounterId1;
  name: Name9;
  scene_id: SceneId1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "ItemCreate".
 */
export interface ItemCreate1 {
  description?: Description7;
  effects?: Effects6;
  name: Name10;
  price?: Price1;
  properties?: Properties1;
  rarity: Rarity1;
  type: Type2;
  weight?: Weight1;
  [k: string]: unknown;
}
export interface Properties1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "MonsterCreate".
 */
export interface MonsterCreate1 {
  actions?: Actions2;
  alignment: Alignment2;
  armor_class: ArmorClass2;
  challenge_rating: ChallengeRating;
  charisma: Charisma2;
  constitution: Constitution2;
  description?: Description8;
  dexterity: Dexterity2;
  effects?: Effects7;
  hit_dice: HitDice2;
  hit_points: HitPoints;
  intelligence: Intelligence2;
  inventory?: Inventory2;
  languages: Languages1;
  legendary_actions?: LegendaryActions;
  name: Name11;
  proficiencies?: Proficiencies1;
  senses?: Senses;
  size: Size1;
  special_abilities?: SpecialAbilities;
  speed: Speed3;
  strength: Strength2;
  type: Type3;
  wisdom: Wisdom2;
  xp: Xp2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "MonsterActionRef".
 */
export interface MonsterActionRef {
  action_id: ActionId;
  display_name?: DisplayName;
}
export interface Senses {
  [k: string]: unknown;
}
export interface Speed3 {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "MonsterResponse".
 */
export interface MonsterResponse {
  actions?: Actions3;
  alignment: Alignment3;
  armor_class: ArmorClass3;
  challenge_rating: ChallengeRating1;
  charisma: Charisma3;
  constitution: Constitution3;
  description?: Description9;
  dexterity: Dexterity3;
  effects?: Effects8;
  hit_dice: HitDice3;
  hit_points: HitPoints1;
  id: Id7;
  intelligence: Intelligence3;
  inventory?: Inventory3;
  languages: Languages2;
  legendary_actions?: LegendaryActions1;
  name: Name12;
  proficiencies?: Proficiencies2;
  senses?: Senses1;
  size: Size2;
  special_abilities?: SpecialAbilities1;
  speed: Speed4;
  strength: Strength3;
  type: Type4;
  wisdom: Wisdom3;
  xp: Xp3;
  [k: string]: unknown;
}
export interface Senses1 {
  [k: string]: unknown;
}
export interface Speed4 {
  [k: string]: number;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SceneOptionResponse".
 */
export interface SceneOptionResponse {
  name: Name13;
  scene_id: SceneId2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SelectCampaignContextRequest".
 */
export interface SelectCampaignContextRequest1 {
  encounter_id: EncounterId2;
  scene_id: SceneId3;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpellCreate".
 */
export interface SpellCreate1 {
  casting_time: CastingTime;
  components?: Components;
  description?: Description10;
  duration: Duration;
  effects?: Effects9;
  level: Level2;
  name: Name14;
  range: Range;
  school: School;
  [k: string]: unknown;
}
export interface Components {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ExportModel`'s JSON-Schema
 * via the `definition` "SpellResponse".
 */
export interface SpellResponse {
  casting_time: CastingTime1;
  components?: Components1;
  description?: Description11;
  duration: Duration1;
  effects?: Effects10;
  id: Id8;
  level: Level3;
  name: Name15;
  range: Range1;
  school: School1;
  [k: string]: unknown;
}
export interface Components1 {
  [k: string]: unknown;
}
