from enum import Enum

class CompendiumErrorCode(str, Enum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    LINKED_TARGET_NOT_FOUND = "LINKED_TARGET_NOT_FOUND" 
    INVALID_LIFECYCLE_TRANSITION = "INVALID_LIFECYCLE_TRANSITION"
    CYCLE_DETECTED = "CYCLE_DETECTED"
