__production_status__ = "gold"
from enum import Enum


class CompendiumErrorCode(str, Enum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    LINKED_TARGET_NOT_FOUND = "LINKED_TARGET_NOT_FOUND"
    INVALID_LIFECYCLE_TRANSITION = "INVALID_LIFECYCLE_TRANSITION"
    CYCLE_DETECTED = "CYCLE_DETECTED"
    PACK_NOT_FOUND = "PACK_NOT_FOUND"
    PACK_ID_CONFLICT = "PACK_ID_CONFLICT"
    DEFINITION_NOT_FOUND = "DEFINITION_NOT_FOUND"
    DEFINITION_ID_CONFLICT = "DEFINITION_ID_CONFLICT"
    DUPLICATE_SLUG = "DUPLICATE_SLUG"
    VERSION_MISMATCH = "VERSION_MISMATCH"
    INVALID_REPLACEMENT_TARGET = "INVALID_REPLACEMENT_TARGET"
    LINKED_TARGET_IN_USE = "LINKED_TARGET_IN_USE"
    ILLEGAL_STATE_DEPENDENCY = "ILLEGAL_STATE_DEPENDENCY"
    GRAPH_CYCLE_DETECTED = "GRAPH_CYCLE_DETECTED"
